services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    ports:
      - "3008:3000"
    env_file:
      - ../.env.local
