services:
  proxy:
    image: nginx:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - app
      - api

  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - api

  api:
    build:
      context: ../api
      dockerfile: ../api/Dockerfile
    volumes:
      - ../api:/app:cached
      - /app/node_modules
    env_file:
      - ../.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
